# Variables about the network configuration for Sulis.

# FQHN of the login node
loginhost: login.sulis.ac.uk

# prefixes of the compute, gpu and fat nodes
cnode_prefix: node
gpunode_prefix: gpu
fatnode_prefix: hmem


